apiVersion: v1
kind: Pod

metadata:
  name: pvc-pod

spec:
  containers:
  - name: app
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 3600"]

    volumeMounts:
    - mountPath: /storage
      name: app-storage

  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: beginner-pvc

